spring.config.import=optional:file:.env[.properties]

spring.application.name=techstars

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.db.export.pg_dump_path=pg_dump

google.sheets.credentials.base64=${GOOGLE_CREDENTIALS_JSON}
google.sheets.spreadsheetId=${GOOGLE_SPREADSHEET_ID}

logging.level.com.example.techstars=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=8080
server.servlet.context-path=/api
